version: "3"

vars:
  TAILWIND_CMD:
    sh: command -v tailwindcss >/dev/null 2>&1 && echo "tailwindcss" || echo "npx tailwindcss@latest"
  GOOSE:
    sh: test -f goose && echo "./goose" || echo "go tool goose"
  DATABASE_URL: postgresql://localhost:5432/pacuare

tasks:
  templ:
    desc: Run templ with integrated server and hot reload
    cmds:
      - templ generate --watch --proxy="http://localhost:8090" --cmd="go run ./main.go" --open-browser=false

  tailwind:
    desc: Watch Tailwind CSS changes
    cmds:
      - "{{.TAILWIND_CMD}} -i ./assets/css/input.css -o ./public/output.css --watch"

  server:
    desc: Run server with Air
    cmds:
      - |
        go tool air \
            --build.cmd "go build -o tmp/bin/main ./main.go" \
            --build.bin "tmp/bin/main" \
            --build.delay "100" \
            --build.exclude_dir "node_modules" \
            --build.include_ext "go" \
            --build.stop_on_error "false" \
            --misc.clean_on_exit true

  dev:
    desc: Start development server with hot reload
    cmds:
      - task --parallel tailwind templ server

  migrate:
    desc: Run database migrations
    cmds:
      - "{{.GOOSE}} postgres {{.DATABASE_URL}} up -dir migrations"
